CsvBuilderPattern/Models/ErrorRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CsvBuilderPattern.Models
{
    public class ErrorRecord
    {
        public string errorCode { get; set; }
        public string errorMessage { get; set; }
        public DateTime TransactionDate { get; set; }

    }
}

CsvBuilderPattern/Controllers/CsvController.cs
using CsvBuilderPattern.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace CsvBuilderPattern.Controllers
{
    public class CsvController : Controller
    {
            

        private List<ErrorRecord> rec;
        string file_path = HostingEnvironment.MapPath("~/Folder/eror.csv");
        private CsvWorking<ErrorRecord> working;



        public CsvController()
        {
            var builder = new CsvBuilder();
            working = new CsvWorking<ErrorRecord>(builder);//initialize the working class
            rec = working.GetRecords(file_path);//initialze the GetRecord method
        }

        public ActionResult Show()
        {
            return View(rec);
        }
        public ActionResult Edit(string errCode)
        {
            var rec1 = rec.Find(e => e.errorCode == errCode);
            //var rec1 = rec.FirstOrDefault(r => r.errorCode == errCode.ToList()[0]);
            return View(rec1);
        }

        [HttpPost]
        public ActionResult Edit(ErrorRecord newVal)
        {
            ErrorRecord Oldval = rec.FirstOrDefault(r => r.errorCode == newVal.errorCode);
            if (Oldval != null)
            {
                Oldval.errorMessage = newVal.errorMessage;
                Oldval.TransactionDate = newVal.TransactionDate;
                //if (newVal.TransactionDate == default(DateTime))
                //{
                //    Oldval.TransactionDate = DateTime.Now;
                //}
                //else
                //{
                //    Oldval.TransactionDate = newVal.TransactionDate;
                //}





            }
            System.IO.File.WriteAllLines(file_path, new[] { "errorCode,errorMessage,TransactionDate" }.Concat(rec.Select(r => $"{r.errorCode},{r.errorMessage},{r.TransactionDate:MM/dd/yyyy HH:mm:ss}")));
            return View("Show", rec);
        }

        //public FileResult Download()
        //{
        //    var records = new List<ErrorRecord>();
        //    var data = System.IO.File.ReadAllBytes(file_path);

        //    return File(data,"text/csv","Update_error.csv");
        //}

        public FileResult DownloadCsv()
        {
            var csv = "errorCode,errorMessage,TransactionDate\n" +
                      string.Join("\n", rec.Select(r =>
                          $"{r.errorCode},{r.errorMessage},{r.TransactionDate:MM/dd/yyyy HH:mm:ss}"));

            byte[] data = System.Text.Encoding.UTF8.GetBytes(csv);
            return File(data, "text/csv", "Errors.csv");
        }

    }

}

CsvBuilderPattern/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsvBuilderPattern.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CsvBuilderPattern/Views/Csv/Edit.cshtml
@model CsvBuilderPattern.Models.ErrorRecord

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ErrorRecord</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.errorCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.errorCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.errorCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.errorMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.errorMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.errorMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Show", "Csv")
</div>

CsvBuilderPattern/Views/Csv/Show.cshtml
@model IEnumerable<CsvBuilderPattern.Models.ErrorRecord>

@{
    ViewBag.Title = "Show";
}

<h2>Show Data</h2>



<p>
    <a href="@Url.Action("DownloadCsv", "Csv")">Download CSV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Error Code</th>
            <th>Error Message</th>
            <th>Transaction Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.errorCode</td>
                <td>@item.errorMessage</td>
                <td>@item.TransactionDate.ToString("MM/dd/yyyy HH:mm:ss")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Csv", new { errCode = item.errorCode }, null)

                </td>
            </tr>
        }
    </tbody>
</table>

CsvBuilderPattern/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

CsvBuilderPattern/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

CsvBuilderPattern/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

CsvBuilderPattern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("CsvData", "Show", "Csv", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>